services:
  log-generator:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - FLASK_APP=${FLASK_APP}
      - FLASK_DEBUG=False
      - FLASK_LOG_PATH=/var/log/log-generator
      - FLASK_LOG_LEVEL=WARNING
      - FLASK_LOG_HEADERS=True
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - /var/log/log-generator:/var/log/log-generator

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - log-generator
