site_name: Log Generator
repo_url: https://github.com/joaovictorvns/log-generator
repo_name: joaovictorvns/log-generator
edit_uri: tree/main/docs

theme:
  name: material
  language: pt-BR
  logo: assets/logo.svg
  favicon: assets/favicon.png
  highlightjs: true
  hljs_languages:
    - python

markdown_extensions:
  - attr_list

extra_css:
  - css/extra.css

plugins:
  - mkdocstrings:
      handlers:
        python:
          paths: [log_generator]